name: mlperf-gptj
channels:
  - defaults
dependencies:
  - python>=3.9
  - pip:
      - torch==2.1.0
      - transformers==4.35.2
      - datasets==2.15.0
      - nltk==3.8.1
      - evaluate==0.4.1
      - absl-py==2.0.0
      - rouge_score==0.1.2
